### ISSUE TITLE
How to get transaction_fee amount before sending BTC?

### ISSUE THREAD

**Issue by marat-chardymov** [coinbase/coinbase-ruby#100]
I sent '0.0002' BTC for test and received same amount, but I was charged with transaction fee '0.00115619' BTC which is higher than number of BTC I've sent. According to this https://community.coinbase.com/t/transaction-fees/7728/4  answer I shouldn't be charged at all, obviously this transaction fee info is outdated. So the question is, where I can get current actual transaction_fee? Can I get it from API?

**Comment by catsky** [comment]
same question, please support

**Comment by sds** [comment]
Hey @marat-chardymov, there is currently no publicly-exposed API for estimating transaction fees at this time. We'll keep this in mind!
