### ISSUE TITLE
Addresses method going not working

### ISSUE THREAD

**Issue by strangelittlemonkey** [coinbase/coinbase-ruby#105]
[19] pry(main)> client.addresses(client.current_user['id'])
Coinbase::Wallet::NotFoundError: Not found
from /usr/local/lib/ruby/gems/2.3/gems/coinbase-4.1.0/lib/coinbase/wallet/api_errors.rb:44:in `check_response_status'

L44 says it's a 404.

**Comment by sds** [comment]
Hey @strangelittlemonkey, can you try with the latest version (4.2.0 at time of writing) and see if you can reproduce? Thanks!

**Comment by sds** [comment]
Closing due to lack of response.
