### ISSUE TITLE
Rename 'send' to non-reserved method nam

### ISSUE THREAD

**Issue by ericmwalsh** [coinbase/coinbase-ruby#111]
This is more of a suggestion than an issue really, sorry if this is in the wrong place.

Is it possible to rename the `send` method for some of the clients (wallet, etc)?

I know it's possible to use `__send__` instead but it's a bit of a hassle and not very Rails/Ruby like to override the "reserved words".

**Comment by sds** [comment]
Hey @ericmwalsh, 

I agree that `send` was not the best of names, but that decision was made long ago and I don't see us changing it without introducing a breaking change. In general, you should always be using `__send__` if you want to send a message to an arbitrary method of an object.

Note that Ruby's core libraries sometimes uses `send` for a method name, e.g. [`UDPSocket.send`](http://ruby-doc.org/stdlib-2.4.0/libdoc/socket/rdoc/UDPSocket.html#method-i-send), so this is not that unorthodox.

Hope this helps!
