### ISSUE TITLE
Return Error Status Code in Coinbase::Wallet::APIError

### ISSUE THREAD

**Issue by ericmwalsh** [coinbase/coinbase-ruby#112]
Is it possible to add the error status code to the error wrappers?  That way we can use ranges // codes in case statements rather than having to specify every error class.

Just a suggestion!

**Comment by ericmwalsh** [comment]
I wouldn't mind throwing up a PR, this is a pretty quick change.

**Comment by sds** [comment]
Hey @ericmwalsh, thanks for the suggestion.

Can you clarify what code this would be? Are you referring to an HTTP status code?

I think the better solution is to define classes that are parents of general classes of error and have the other classes subclass those. So you would have a `ClientError` class which is a superclass of all 4XX-related errors.

Happy to accept a pull request!

**Comment by mufudzimasaire** [comment]
Hey @sds, I noticed this open issue whilst having a play with the gem and I couldn't help but indulge myself. Please consider this smallish PR https://github.com/coinbase/coinbase-ruby/pull/115 ...

**Comment by Nantaya555** [comment]
Good

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
