### ISSUE TITLE
Inquiry about ROI features

### ISSUE THREAD

**Issue by alex0112** [coinbase/coinbase-ruby#113]
I've been working on a project using the coinbase-ruby gem to calculate the ROI for each currency I own.  I've ended up creating (or intending to create) functionality which gets data from the API and performs a few simple calculations on it.  As I've done so I've wondered if these features would be better suited to the actual gem.  I wanted to reach out and see if the maintainers of the project would be interested in merging pull requests implementing some or all of the following interfaces:

- USD invested
- USD lost
- USD gained (or ROI)
- Current cash-in value (or, ROI taking into account transaction fees)

These features could be useful for people creating bots to watch the market and sell when a certain ROI is reached.

### Example:
Something like the following program:

```ruby
client       = Coinbase::Wallet::Client.new(api_key: API_KEY, api_secret: API_secret)
btc          = client.account(:BTC)
usd_invested = btc.usd_invested ## => {"amount"=>"167.45", "currency"=>"USD"}
usd_gained   = btc.usd_gained   ## => {"amount"=>"10.67", "currency"=>"USD"}
usd_lost     = btc.usd_lost     ## => {"amount"=>"0.00", "currency"=>"USD"}
roi          = btc.usd_roi      ## => {"amount"=>"9.17", "currency"=>"USD"}
```

If these interfaces sound useful to anyone, let me know.  Otherwise, I'll just continue to implement them on my side of things.

**Comment by sds** [comment]
Hey @alex0112, thanks for suggesting great feature ideas for this gem.

At this point in time, we'd like to keep this gem focused on the facilitation of transactions and general wallet management, rather than introduce other concepts such as ROI.

Highly encourage you to publish such functionality as a separate gem, however!
