### ISSUE TITLE
OAuth Token Refresh Issue

### ISSUE THREAD

**Issue by mchalise** [coinbase/coinbase-ruby#114]
When using command    `Client.refresh!`  I am getting this error.
The request is missing a required parameter, includes an unsupported parameter value, or is otherwise malformed.

**Comment by sds** [comment]
Hey @mchalise, can you read [this similar thread](https://github.com/coinbase/coinbase-ruby/issues/109#issuecomment-371679450) to see if it helps?

**Comment by sds** [comment]
Since you posted in the other thread, will close this as a duplicate.
