### ISSUE TITLE
Coinbase::Wallet::APIError - [410]

### ISSUE THREAD

**Issue by nazrulcse** [coinbase/coinbase-ruby#117]
It was working fine but in recent getting the following error. 
Coinbase::Wallet::APIError - [410] {"errors"=>[{"id"=>"gone", "message"=>"Merchant Services have been deprecated"}]}

**Comment by sds** [comment]
Hey @nazrulcse,

Merchant tools have been [deprecated as of May 31st](https://medium.com/@coinbasecommerce/update-deprecating-coinbase-merchant-tools-3e6d9d9357df). If you have further questions about your account, please open a [support ticket](https://support.coinbase.com). Thanks!
