### ISSUE TITLE
Invalid amount

### ISSUE THREAD

**Issue by yegor256** [coinbase/coinbase-ruby#119]
When I'm trying to send BTC I'm getting "Invalid amount" exception with no additional details. My code:

```ruby
acc.send(
  to: '1DbN9gKEDkSuyCBsNEBrZkYTy5VLUXYGiK',  
  amount: '0.0002878427', 
  currency: 'BTC',
  description: 'hello'
)
```

What's wrong? See https://twitter.com/yegor256/status/1072384262048022529

**Comment by Subomi** [comment]
@yegor256 How did you fix this? .. I'm receiving similar error?

**Comment by Subomi** [comment]
@yegor256 so at my place, we found out that coinbase only throws this error when the numbers behind the decimal place is greater than 9. Keeping it at 8 is a safe bet for you.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
