### ISSUE TITLE
Coinbase API 4.2.1 Account Request Method, Missing parameter: `type`

### ISSUE THREAD

**Issue by ekr990011** [coinbase/coinbase-ruby#124]
https://stackoverflow.com/questions/58106602/coinbase-api-4-2-1-account-request-method-missing-parameter-type

After I connect with my api keys I simply wanted to setup a request for funds.
I have gone through and the path is correct, the headers appear to be correct and the params are correct. (to, amount, currency, type) are all in the params for the post request. The api returns a 400 error with Coinbase::Wallet::ParamRequiredError (Missing parameter: `type`).

I am unsure why this is happening on the api end because the type "request" is sent with my POST.

Possibly something needing to be fixed in the setting up of the post that the backend api doesn't like?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
