### ISSUE TITLE
Transactions search

### ISSUE THREAD

**Issue by ilyakatz** [coinbase/coinbase-ruby#52]
Is it possible to search transactions where bitcoin was sent to a particular wallet? If no, where is the best place to ask for a feature request for the api?

**Comment by ilyakatz** [comment]
@jorilallo does this mean this is not happening or has it been done?

**Comment by jorilallo** [comment]
@ilyakatz I cleaned old issues for the new release (APIv2). Unfortunately we don't have TX search yet but we're planning to add it later. I'll have a note about this in our internal systems and I'll keep this closed as this issue isn't really related to one specific client library. Please subscribe to our [developer blog](https://developers.coinbase.com/blog) for updates on this

**Comment by jorilallo** [comment]
@ilyakatz Small update: I added a new endpoint to get transactions for a specific address: https://developers.coinbase.com/api/v2#list-address39s-transactions This has also been added to our new ruby gem (4.0.3)

**Comment by ilyakatz** [comment]
nice, thank you!
