### ISSUE TITLE
NoMethodError Exception: undefined method `to_money'

### ISSUE THREAD

**Issue by Sjors** [coinbase/coinbase-ruby#58]
I get this when I call `coinbase.balance` or ` coinbase.create_button`. The error message contains the correct balance, so it seems my login credentials are correct.

Using Rails 4.2.0 and Ruby 2.2.0. I suspect something changed in the money gem recently.

Here's an example project where this fails: [Bitcoin Passbook](https://github.com/Sjors/bitcoin-passbook)

**Comment by aianus** [comment]
Hmm I haven't heard of this happening for anyone else.

Can you post the entire stack trace for the error? As well as your Gemfile.lock?
