### ISSUE TITLE
Coinbase blocks rails 4.2.0

### ISSUE THREAD

**Issue by saizai** [coinbase/coinbase-ruby#63]
Fixed by #59 but gem needs to be bumped.

**Comment by saizai** [comment]
@aianus Ping?

**Comment by aianus** [comment]
Can you use

```ruby
gem 'coinbase', github: 'coinbase/coinbase-ruby', branch: 'v3'
```

in the meantime?

**Comment by saizai** [comment]
Possibly, but that's a poor solution for everyone who uses the gem. Is
there anything blocking just bumping the version? The fix has already been
committed…

**Comment by saizai** [comment]
Also, no, because:
    omniauth-coinbase (>= 1.0.2) ruby depends on
      coinbase (~> 2.0) ruby

**Comment by JacobEvelyn** [comment]
+1, this gem needs to be better maintained!

**Comment by saizai** [comment]
This seems to have been integrated.
