### ISSUE TITLE
HMAC Authentication

### ISSUE THREAD

**Issue by pinklin** [coinbase/coinbase-ruby#67]
Hi,
    To intergrate the coinbase methods currently am checking them on rails console. The hmac authentication "coinbase = Coinbase::Client.new(ENV['COINBASE_API_KEY'], ENV['COINBASE_API_SECRET']) when run shows TypeError: no implicit conversion of Symbol into Integer error". What has to be done to solve this ?

**Comment by pinklin** [comment]
Can anybody respond to this issue ? Its urgent.

**Comment by jorilallo** [comment]
I think you're setting the key and the secret as symbols instead of string (`:value` != "value"). Try using the strings directly.

**Comment by pinklin** [comment]
coinbase = Coinbase::Client.new("xxxxxxxxx", "yyyyyyyyy"). Tried hard coding like above, still get TypeError: no implicit conversion of Symbol into Integer error".

**Comment by jwietelmann** [comment]
Same issue here. Thought maybe it was something weird with the dotenv gem, but hardcoding the key and secret as strings still breaks for me too. This issue should not be closed.

ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-darwin14.0]

```
irb(main):001:0> Coinbase::Client.new '...', '...'
TypeError: no implicit conversion of Symbol into Integer
	from /opt/boxen/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/coinbase-1.2.4/lib/coinbase/client.rb:16:in `[]'
	from /opt/boxen/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/coinbase-1.2.4/lib/coinbase/client.rb:16:in `initialize'
	from (irb):1:in `new'
	from (irb):1
	from /opt/boxen/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.0.12/lib/rails/commands/console.rb:90:in `start'
	from /opt/boxen/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.0.12/lib/rails/commands/console.rb:9:in `start'
	from /opt/boxen/rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.0.12/lib/rails/commands.rb:62:in `<top (required)>'
	from ./bin/rails:4:in `require'
	from ./bin/rails:4:in `<main>'
```

**Comment by jwietelmann** [comment]
Found that an outdated `jwt` Gemfile entry was preventing `coinbase` from installing the latest versions. Was stuck on 1.2.4.

**Comment by jorilallo** [comment]
@jwietelmann is it working now?

**Comment by jwietelmann** [comment]
It is. The issue @pinklin is having is probably a similarly outdated version of the gem.

**Comment by jorilallo** [comment]
@pinklin want to check out the version?

**Comment by JacobEvelyn** [comment]
I get this error as well, because the versions of Coinbase on RubyGems all require an old version of `monetize` (which was updated with 6a7186288ff742a8bee56820865c4b2100d1a2bc), when my app uses a more recent version. A new release would be nice.
