### ISSUE TITLE
client.sell_price returns wrong price

### ISSUE THREAD

**Issue by sangyongjung** [coinbase/coinbase-ruby#77]
This is more of problem of api itself than of coinbase-ruby library, I guess.
When I get the selling price with 'client.sell_price', the price returned is the sell price on coinbase website plus 1% commission.
Since the sell price is amount user 'receives' after selling btc, commission should be subtracted instead of added, am I right?

**Comment by sangyongjung** [comment]
It's related issue with the former one.
When I try 'account.sell(amount: "1", currency: "BTC", quote: true)' to get the price instead of client.sell_price, it returns 'Required parameter missing: currency' error.

**Comment by jorilallo** [comment]
You're correct on this. We'll be pushing a fix later today to address this.
