### ISSUE TITLE
'Required parameter missing: currency' error

### ISSUE THREAD

**Issue by sangyongjung** [coinbase/coinbase-ruby#78]
It's related issue with the former one.
When I try 'account.sell(amount: "1", currency: "BTC", quote: true)' to get the price instead of client.sell_price, it returns 'Required parameter missing: currency' error.

**Comment by jorilallo** [comment]
thanks for this and the other issues, it seems that we weren't passing `params` on multiple endpoints. I'll be fixing this now and pushing out a new version (4.0.7)

**Comment by jorilallo** [comment]
New version released

**Comment by sangyongjung** [comment]
Thank you! This is solved.

**Comment by Aatika-Fatima** [comment]
public function sellOrder($account_id, $body) {
		echo $body;
		$url = "https://api.coinbase.com/v2/accounts/" . $account_id . "/sells";
		$headers = $this->genearateCoinbaseHeaders();
		$response = $this->sendRequest ( $url, 'POST', json_encode ( $body ), $headers );
		list ( $rawHeaders, $rawBody ) = $this->extractResponseHeadersAndBody ( $response );
		$data = json_decode ( $rawBody, true );
		print_r ( $data );
		return $data;
	}

public function genearateCoinbaseHeaders() {
		$headers [] = 'Authorization: Bearer ' . $this->accessToken;
		$headers [] = 'CB-VERSION: 2018-10-22';
		return $headers;
	}

error: ArrayArray ( [errors] => Array ( [0] => Array ( [id] => param_required [message] => Required parameter missing: currency ) ) )
