### ISSUE TITLE
require 'coinbase/wallet' in Gemfile

### ISSUE THREAD

**Issue by rebeccacaroline** [coinbase/coinbase-ruby#81]
I was having a problem with sending money via Coinbase - even though I had installed the coinbase gem and had require 'coinbase/wallet' in the file where I was making the api call, I was getting a LoadError that 'coinbase/wallet' could not be loaded. 

Once I required 'coinbase/wallet' in my Gemfile, the error went away and the payments worked. 
`gem 'coinbase', '~> 4.0.7', require: 'coinbase/wallet'`

It would be helpful to add that to the documentation.

**Comment by jorilallo** [comment]
I think this must be something with your environment as installing and requiring in the file should work just fine. @aianus thoughts?
