### ISSUE TITLE
BigDecimal dependency breaks in Rubinus

### ISSUE THREAD

**Issue by saizai** [coinbase/coinbase-ruby#84]
See https://github.com/coinbase/coinbase-ruby/pull/83

**Comment by jorilallo** [comment]
Thanks, I'll remove the dependency

**Comment by saizai** [comment]
@jorilallo Sure. :-) Could you bump the gem? This issue is causing bundle update to break.

**Comment by jorilallo** [comment]
@saizai Bumped today!
