### ISSUE TITLE
buy_price and sell_price only return BTH-USD

### ISSUE THREAD

**Issue by flah00** [coinbase/coinbase-ruby#95]
```ruby
#!/usr/bin/env ruby
require 'coinbase/wallet'
c=Coinbase::Wallet::Client.new
puts c.buy_price(currency_pair: 'ETH-USD')
puts c.sell_price(currency_pair: 'ETH-USD')
```

```console
{"amount"=>"1217.77", "currency"=>"USD"}
{"amount"=>"1193.58", "currency"=>"USD"}
```

It seems like the problem is `coinbase/wallet/api_client.rb` `#buy_price` and `#sell_price` do not use the `params`. I changed the methods to accept a `currency_pair` argument, and added that to the URL and now I get the results I expect.

**Comment by flah00** [comment]
Documentation in the readme.md, for `#buy_price` and `#sell_price` (refers to key `currency`) differ from the [online docs](https://developers.coinbase.com/api/v2?ruby#get-buy-price) (refers to key `currency_pair`. The `currency` fails, when using `BTC-USD`. The `currency_pair` doesn't seem to have any effect on the request.

**Comment by tmlee** [comment]
What version of the gem are you using that got you that result? @flah00 
On master branch, it seems to be alright for me
```ruby
puts c.buy_price(currency_pair: 'ETH-USD')
{"amount"=>"42.18", "currency"=>"USD"}
puts c.sell_price(currency_pair: 'ETH-USD')
{"amount"=>"41.32", "currency"=>"USD"}
```

And you are right about the documentation, that can be updated to use `currency_pair`; perhaps a good idea to fix that once its validated that the `buy_price` `sell_price` API works for you as expected

**Comment by flah00** [comment]
@tmlee I noticed the coinbase/wallet/VERSION.rb file was updated in 2015, but there were commits to the repo in 2016. I guess the changes were never pushed up to rubygems? 

```console
$ gem install coinbase
Fetching: coinbase-4.1.0.gem (100%)
Successfully installed coinbase-4.1.0
1 gem installed
$ irb -rcoinbase/wallet
irb(main):014:0> Coinbase::Wallet::VERSION
=> "4.1.0"
irb(main):011:0> c=Coinbase::Wallet::Client.new({api_key:"",api_secret:""})
=> #<Coinbase::Wallet::Client:0x000000012d49d8 @api_key="", @api_secret="", @api_uri=#<URI::HTTPS https://api.coinbase.com>, @conn=#<Net::HTTP api.coinbase.com:443 open=false>>
irb(main):013:0> puts c.buy_price(currency_pair: 'ETH-USD')
{"amount"=>"1048.37", "currency"=>"USD"}
irb(main):015:0> puts c.sell_price(currency_pair: 'ETH-USD')
{"amount"=>"1027.64", "currency"=>"USD"}
```

**Comment by CodingAnarchy** [comment]
It appears to me that those changes to use `currency_pair` were not pushed up in a new version of the gem to rubygems.

**Comment by parabuzzle** [comment]
I can confirm that the `currency_pair` stuff is not in the packaged gem. Please cut a new gem.

**Comment by dave315** [comment]
Confirm and big time +1

**Comment by xiaosongmu** [comment]
This issue should be re-opened

**Comment by mattdperkins** [comment]
Same issue

**Comment by scarrick68** [comment]
You guys are right. The `determine_currency_pair` function was added 6 months after the last release. I added this to my gem file to use the latest commit SHA in master `gem 'coinbase', :git => 'https://github.com/coinbase/coinbase-ruby.git', :ref => '51780c7b7e65adc805e061926b1138db83b7bcb1'`Pointing to master will also work, but who knows if they'll update it again

**Comment by alexbeeken** [comment]
I'm seeing this issue today! I'll point my gem to github but just lyk.

**Comment by sds** [comment]
Apologies for the delay. Version [4.2.0](https://rubygems.org/gems/coinbase/versions/4.2.0) has been released!
