### ISSUE TITLE
How to supply the API version.

### ISSUE THREAD

**Issue by macgregordennis** [coinbase/coinbase-ruby#96]
Each time I execute a method, the following warning is now returned:

`WARNING: Please supply API version (YYYY-MM-DD) as CB-VERSION header (https://developers.coinbase.com/api#versioning)`

How do I supply the API version through the gem?

**Comment by justinpobrien** [comment]
This should do it: 
```
client = Coinbase::Wallet::Client.new(api_key: <api key>,
                                      api_secret: <api secret>,
                                      CB_VERSION: 'YYYY-MM-DD')
```

**Comment by gravaman** [comment]
Having a similar issue here... tried the above but still receiving a warning.
